name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Login to Docker hub
        run: docker login -u runaksh -p Pwcwelcome@1234 
      - name: Pull Docker Image
        run: sudo docker pull runaksh/bikeshare-fastapi:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f bikeshare-fastapi-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name bikeshare-fastapi-container runaksh/bikeshare-fastapi
